### ISSUE TITLE
404 Unknown Interaction 

### ISSUE THREAD

**Issue by incogsavage** [ExoticCitron/discord-music-bot#1]
i sometimes get interaction failed when playing a song why?

**Comment by ExoticCitron** [comment]
would be hard to tell if i dont get some sort of log? what does the logger say? should be on your terminal

**Comment by incogsavage** [comment]
404 unknown interaction for volume, i removed command

**Comment by ExoticCitron** [comment]
> 404 unknown interaction for volume, i removed command

why did you remove it? ofc it wont work if you restart it
re-add the command (link to the src/spotify.py), it's needed to alter vc volume using PCMVolumeTransformer

once you add that, resync the bot and we should be good :'j

**Comment by incogsavage** [comment]
it worked, thanks!

**Comment by incogsavage** [comment]
thank you
