### ISSUE TITLE
Doesn't work without ffmpeg installed.

### ISSUE THREAD

**Issue by Daniel-191** [ExoticCitron/discord-music-bot#3]
You need ffmpeg installed for this to work. Currently running the bot on windows, without ffmpeg installed and added to path etc etc, the bot will give you some handshake error.

This is the guide I followed to installed ffmpeg - https://transloadit.com/devtips/how-to-install-ffmpeg-on-windows-a-complete-guide/

**Comment by ExoticCitron** [comment]
i'm a silly goose, this was a required prerequisite to play music, i recently switched this from pre-encoded opus files since ffmpeg was the best when i researched on it. Thanks for bringing this to my attention, i'll be editing the README to include this

Thanks once again

**Comment by Daniel-191** [comment]
np
